hub/executor/executor.go
ClashX will use it to determine if the 'Meta' has finished booting
=> ApplyConfig finish log.

adapter/outboundgroup/fallback.go, adapter/outboundgroup/groupbase.go, adapter/outboundgroup/loadbalance.go, adapter/outboundgroup/parser.go, adapter/outboundgroup/relay.go, adapter/outboundgroup/selector.go, adapter/outboundgroup/urltest.go, adapter/provider/parser.go, adapter/provider/provider.go, common/convert/converter.go
proxy-provider 和proxy-groups 支持通过节点类型排除
proxy-provider and proxy-groups support exclude node by node type
proxy-provider example:
```yaml
proxy-providers:
xxxxx:
type: http
url: xxxxxx
path: xxx
#filter: "xxx"  #支持正则表达式根据节点名称筛选
#exclude-filter: "xxx" #支持正则表达式根据节点名称排除
exclude-type: "ss|http" #不支持正则表达式，通过 "|" 分割，根据节点类型排除
interval: 3600
health-check:
enable: true
url: http://www.gstatic.com/generate_204
interval: 3600
```
proxy-groups example:
https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/constant/adapters.go
```yaml
proxy-groups:
- name: XXX
type: url-test
#filter: "xxx" #支持正则表达式根据节点名称筛选
#exclude-filter: "xxx" #支持正则表达式根据节点名称排除
exclude-type: "Shadowsocks|Http" #不支持正则表达式，通过 "|" 分割，根据节点类型排除,注意，名称与proxy-providers不同
use:
-xxxxx
proxies:
- xxxx
url: "http://www.gstatic.com/generate_204" …
```
=> proxy-provider and proxy-groups support exclude node by node type

flake.nix
Update `vendorSha256` to keep `flake.nix` in sync with `go.sum`.
=> Update flake.nix hash

adapter/outbound/vless.go, component/tls/config.go
=> fix: get tlsconfig err not handle, return nil pointer #358

component/nat/table.go, constant/adapters.go, listener/shadowsocks/utils.go, listener/sing/sing.go, listener/socks/utils.go, listener/tproxy/packet.go, listener/tunnel/packet.go, transport/tuic/server.go, tunnel/connection.go, tunnel/tunnel.go
目前Clash处理TPROXY时采用不断开启/关闭本地Socket模式处理，导致在Socket开启时的分组丢失，从而产生了很多问题，这个补丁修复了这个问题，并增加了一定的性能（UDP双向测试时CPU从25%下降到15%）。
TPROXY模块在Linux内核中实现时做了优化，对已经存在Transparent Socket的链接会直接使用而不会继续重定向；不断开启关闭Socks会导致不必要的性能消耗，同时也会导致Socks存在时的系统的UDP分组丢失（因为没有读取）。
目前遇到的比较严重的问题
- 单核心设备使用TPROXY处理Wireguard（包括其他内核模块也有类似问题）时，TCP断流、无法正常使用
- 单核心设备在双向UDP通信时，随机丢包
- TPROXY的UDP性能差，对比V2RAY等软件，在同等负载下即使是Direct内网环境下，CPU/延迟/丢包抖动等指标均不理想；且随机性丢包和延迟问题较为明显
- 多核心设备使用TPROXY处理Wireguard时，虽然能缓解TCP断流的问题，依然存在大量的TCP重传，非常影响性能，同时也不稳定
复现方法较为简单，可以直接采用最容易复现的Wireguard，以下测试基于以下环境测试
1.在Vultr创建两台同区域的服务器，我选择1 Core款任意配置
2.安装最新版Wireguard/iperf3，并设置妥当；其中主动链接一方使用TPROXY重定向、作为iperf3客户端
3.设置好iptables tproxy规则
4.分别上传Alpha版的Clash.Meta和补丁后的Clash.Meta
5.设置Clash为Direct模式
6.使用Wireguard的端内IP执行iperf3测试
因为Wireguard为纯UDP协议，所以产生的隧道流量都会被重新组装为UDP。 …
=> 修复TPROXY处理UDP时的问题

adapter/inbound/socket.go, component/http/http.go, listener/inner/tcp.go
- 启动阶段，executor还未初始化tunnel，tcpIn==nil导致geo下载失败,阻塞在 tcpIn <- context
=> fixes #512: geo download failed when startup

component/dialer/bind.go, component/iface/iface.go
在ArchLinux上测试通过
在Android上偶尔会报内存问题，由于对于项目架构不了解，该问题超出了本人能力范围，暂时无法解决
内存部分日志如下
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x644ae845e0]
goroutine 366 [running]:
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0x4000506510, {0x644b86fba8?, 0x4000e4c7b0}, {0x4000048690, 0x23}, {0x0?, 0x0, 0x4000526000?}, 0x40000a7e08?)
github.com/Dreamacro/clash/adapter/adapter.go:290 +0x550
github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).execute.func1()
github.com/Dreamacro/clash/adapter/provider/healthcheck.go:211 +0x17c
github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go.func1()
github.com/Dreamacro/clash/common/batch/batch.go:52 +0xec
created by …
```
=> fix hysteria faketcp lookback in TUN mode

adapter/adapter.go, adapter/outboundgroup/parser.go, adapter/provider/healthcheck.go, constant/adapters.go
+ When testing the delay through REST API, determine whether to store the delay data based on certain conditions instead of discarding it directly
=> [Feature] Check if storage is available before discarding data generated through the delay testing via REST API

adapter/adapter.go, adapter/outbound/hysteria.go, adapter/outbound/socks5.go, adapter/outbound/trojan.go, adapter/outbound/util.go, adapter/outbound/vmess.go
延迟测速时(/api/delay)，经常会有超过设置timeout的情况。
比如yacd设置了2000ms timout，但是这个api耗费了5秒甚至10秒多才返回，很烦人。
原因是在各个协议协商阶段并没有设置context，且当连接在超时时间内建立，但是回包一直没有到达时(StreamConn方法)，测速会一直挂起。很难受。
此PR修复该问题。经测试，修复后前端调用该api的耗时稳定在期望的2秒。
=> Fix: Enforce conn context 修复延迟测速耗时超过timeout

adapter/outbound/shadowsocks.go, go.mod, go.sum
Hi,
Sorry for the delay. We were working on this update throughout the entire week. 
Off topic:
It turns out we were among the few projects leveraging session resumption (we don't rebuild the TLS Config per connection). This led us down many rarely traversed paths, which hadn't been tested for years. Pinpointing and resolving these issues was time-consuming.  
Our efforts culminated in the introduction of a long-awaited feature in uTLS: PSK-based session resumption for TLS 1.3. We're in the final stages of our work, anticipating its integration into uTLS. Implementing the PSK feature will enhance parroting, aligning utls clients more closely with browsers, especially given that recent Chrome versions utilize PSK-based sessions for TLS 1.3.
=> feat: bump restls to v0.1.5 (utls v1.4.3)

hub/route/restart.go
当我使用 Api 来重启或更新 Meta 内核时，会出现 iptables 规则重复的情况。查看代码后发现是调用 `runRestart` 的时候没有清除 iptables。
我直接用 `executor.Shutdown()` 替换掉原来的 `listener.Cleanup(false)`，问题得到解决。
以下内容是因为在重启时没有清除规则导致的规则重复，这导致彻底退出 Meta 后也会残留部分规则，最终影响路由。
```
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:clash_dns_output - [0:0]
-A PREROUTING ! -s 172.17.0.0/16 ! -d 127.0.0.0/8 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING ! -s 172.17.0.0/16 ! -d 127.0.0.0/8 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING ! -s 172.17.0.0/16 ! -d 127.0.0.0/8 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING ! -s 172.17.0.0/16 ! -d 127.0.0.0/8 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING ! -s 172.17.0.0/16 ! -d 127.0.0.0/8 -p udp …
```
=> fix: call shutdown() before restart

hub/executor/executor.go, listener/listener.go
Let the restful api still get TunConf even when tun is off. Otherwise the api will return the default values,
instead of the values that actually take effect after enable.
\* Due to this problem, yacd changes the displayed value back to gvisor immediately after the user selects tun stack.
---
[/listener/listener.go#L85-L92](https://github.com/MetaCubeX/Clash.Meta/blob/65071ea7d16724ef3262366f0c0877b4a73d815b/listener/listener.go#L85-L92)
```go
func GetTunConf() LC.Tun {
if tunLister == nil {
return LC.Tun{
Enable: false,
}
}
return tunLister.Config()
}
```
The `GET /configs` interface currently returns the information provided by this function, and attributes other than `Enable` will be filled with default values. 
When the configuration of the tun is changed, the tun device will be …
=> Improve: nicer tun info for RESTful api

hub/executor/executor.go, listener/listener.go
There is a mistake in my last commit 54fee7bd3a57ddd589a96f80b893b8524a9adf4f, which will cause once the `tun.device` is not explicitly configured, the RESTful api would fail to obtain the tun device name even if the tun device has already running.
This is because the default device name is specified directly by `sing_tun.server` instead of `LC.tun{}`. Thus it is necessary to get the current config directly when `tunLister` is available, so I reverted the changes to the executor.
-----
As for the second commit about Cleanup, I found that it is actually used in two places in `ReCreateTun`, but only one may take effect, and its modification to `LastTunConf` will always be reset.
Moreover, if other listeners have content,  such as ip link or ip rule, that needs to be cleaned up when the …
=> Fix restful api get tun conf.device, and clean Cleanup function

component/sniffer/dispatcher.go, tunnel/tunnel.go
This PR tries to handle some connection failure caused by Fake DNS cache invalidation, which usually happens in a setup where some caching DNS servers (like ADGuard Home) are using Clash's Fake DNS server as their upstream, with certain policy-based-routing implemented by examining the result of DNS queries. 
The cache invalidation would occur if either of the following is met
- the `cache.db` is corrupted for any reason (like switching to Clash Premium back and forth. I am migrating from Premium to Meta recently)
- the Clash just restarted without properly storing the fake DNS cache
- the `store-fake-ip` is set to `false` and some caching DNS servers are yet to be synchronized with the new value.
It is really hard to deny, that for simpler setups, the best solution is clearing the DNS …
=> feat: recovering `preHandleMetadata` failure from sniffing

adapter/provider/subscription_info.go
do not use regex parsing for `Subscription-UserInfo` header field
=> chore: improve subscription userinfo parsing

hub/route/server.go
New version of Clash for Windows uses `ws://external-controller/logs?token=&level=info&format=structured` to get real time log. When Clash Premium Core reveices `format=structured`, it returns a different form of JSON log entry. Supporting this feature will allow better Clash for Windows integration
=> feat: support clash premium's structured log stream

adapter/outbound/hysteria.go, adapter/outbound/hysteria2.go, adapter/outbound/shadowsocks.go, adapter/outbound/singmux.go, adapter/outbound/vmess.go, transport/hysteria/core/client.go
`metadata.RemoteAddress()` is implemented with `net.JoinHostPort`:
https://github.com/MetaCubeX/Clash.Meta/blob/fdd327d58da49b0bf21b0908bc7e3d475eae63a3/constant/metadata.go#L154-L157
However, most use cases of `RemoteAddress()` is passing it to `M.ParseSocksaddr`, which is implemented with `net.SplitHostPort`
https://github.com/MetaCubeX/sing/blob/f9766a597f7dbd6919a9b60c1eb1e41221e3ab1d/common/metadata/addr.go#L186-L195
Those redundant string concatenations can be ruled out by making use of `M.ParseSocksaddrHostPort`.
=> chore: reduce string split immediately after string concat

config/config.go
To pass compile of Clash Meta for Android
This member exists in Kr238's patched clash core for android (https://github.com/Kr328/clash/blob/68b653837decdb889045ed5525013b73509ad94d/config/config.go#L157)
But missing in clash meta core
Related issue: #799
=> fix: add a missing config member in android patch

rules/provider/classical_strategy.go
Logic rules like AND,OR,SUB-RULE, etc have a different rule structure than traditional rules. The parser used in ./config/config.go was updated accordingly when adding these rule types but the parser used  in ./rules/provider/parse.go was not, making logic rules in remote providers not working as expected.
=> fix: remote logic rules cannot be parsed

adapter/adapter.go
Usually,`history` is used to store the latency generated by healthcheck of `ProxyProvider`, while `extra` stores the latency generated by testURL configured in each ProxyGroup. Therefore, when updating the `extra` data, it should not overwrite the `history`.
=> [fix] latency of extra should not overwrite the history

config/config.go, config/update_geo.go, config/update_ui.go, constant/geodata.go, docs/config.yaml, main.go
1. Introduction of `geo-auto-update` and `geo-update-interval` Configuration Items
`geo-auto-update` : This flag controls the automatic updating of the geo data file. It is set to false by default, ensuring that auto-updates are opt-in rather than automatic.
`geo-update-interval` : This parameter defines the interval (in hours) for the geo data file auto-update process. The default value is set to 24 hours, providing a daily update cycle when geo-auto-update is enabled.
2. Bug Fix: Accurate Error Handling in `saveFile` Function
The original code did not correctly capture and relay errors encountered during the file saving process.
Previous Implementation:
```go
data, err := downloadForBytes(ExternalUIURL)
if err != nil {
return fmt.Errorf("can't download  file: %w", err)
}
saved := …
```
=> feat: Add GeoAutoUpdate and GeoUpdateInterval to config

adapter/inbound/ipfilter.go, config/config.go, docs/config.yaml, hub/executor/executor.go, hub/route/configs.go, listener/http/proxy.go, listener/socks/tcp.go
This PR introduces two new configuration options: `lan-allowed-ips` and `lan-disallowed-ips`. 
This feature will be useful for users who need precise control over their LAN proxy access, such as in corporate environments or shared networks. This provides additional control and security protection beyond username and password.
=> feat: Add LAN allowed and disallowed IP configurations

component/process/process_windows.go
不要走远路，走对路。
This PR reverts https://github.com/MetaCubeX/mihomo/commit/1b527fd494e8b2ad713ea0afcf9af485d452d61c.
This PR may also fixes #908.
=> fix: the right way to get process name in win32 format

adapter/outboundgroup/urltest.go, constant/adapters.go
89da296
由于 [这个修改](https://github.com/MetaCubeX/mihomo/pull/588) ，`url-test` 将不再使用最新 `delay` 测试作为排序结果，导致如果 api 传入 url 和 `url-test` 默认值不符的时候并不会采用此时测量所得的延迟进行排序。
现修改 `url-test` 组延迟测试逻辑为强制使用 `url-test` 的 `health-check.url`，使得每次按组测试后可正常触发重新选择
8f10ce4
更新默认 `healthcheck.url` 到 `https://www.gstatic.com/generate_204`
=> fix && chore

hub/route/server.go
自从 `chrome 98` 开始，google 提出了一个新的功能，[对专用网络资源访问进行预检](https://chromestatus.com/feature/5737414355058688) ，它的前身是来自 W3C 社区的 [此草案](https://wicg.github.io/private-network-access/) 。在高版本 chrome 中已出现因此无法使用网络面板进行控制的情况（特指搭载在开放网络上的公用网络面板而非由核心拉起的本地网络面板），故对 `Preflight request` 添加相应响应头，使浏览器按预期进行工作。
=> chore: add a new cors response header

listener/http/proxy.go
fix https://github.com/MetaCubeX/mihomo/issues/951
=> fix: add backgroundRead for plain http inbound

common/convert/converter.go
fix: ss obfsParams parsing index out of range
feat: support ss v2ray-plugin parsing
feat: support hy2 schema parsing
=> fix: ss obfsParams parsing index out of range

adapter/inbound/addition.go, constant/metadata.go, constant/rule.go, listener/tproxy/setsockopt_linux.go, listener/tproxy/udp.go, listener/tproxy/udp_linux.go, listener/tproxy/udp_other.go, rules/common/dscp.go, rules/parser.go
为 Tproxy 模式下的 UDP 包增加 DSCP 规则，使得 UDP 可以根据其 IP 报文头部的 DSCP 进行分流。
在 Windows 下，可以设置 [QoS 策略](https://learn.microsoft.com/en-us/windows-server/networking/technologies/qos/qos-policy-manage)，此策略可以根据进程修改 IP 报文的 DSCP；在 Linux 下，可以通过 [iptables](https://ipset.netfilter.org/iptables-extensions.man.html#:~:text=for%20translated%20flows.-,DSCP,-This%20target%20allows) 等用户态工具为应用或用户修改 IP 报文的 DSCP。从而，在开启 Tproxy 的透明代理模式下，通过 DSCP 规则进行 UDP 分流可以等效地实现针对代理下客户端的分应用 UDP 分流或分用户 UDP 分流。
=> feat: add DSCP rule for Tproxy UDP packets

adapter/adapter.go, docs/config.yaml
+ 优化 #860 的修改，`history` 里存原始的延迟数据，`extra` 里存响应状态码与  `expected-status`（如有配置） 比较后的数据
=> store latency data more reasonably

listener/http/proxy.go
relate to https://github.com/MetaCubeX/mihomo/pull/952#issuecomment-2118639385
=> chore: stop using go:linkname for http.registerOnHitEOF, http.requestBodyRemains

listener/tproxy/packet.go
tproxy panic randomly when running for a long time
=> fix(listener/tproxy): possilly using released buffer in tproxy

common/convert/converter.go
It should be a string for the following reasons:
1. During conversion, it is conditionally assigned with `wsOpts["path"] = path.(string)`
2. After conversion, it is decoded into `WSOptions.Path` in `adapter/outbound/vmess.go` which requires a string.
=> fix: correct type for vmess.ws-opts.path in ConvertsV2Ray

dns/system_windows.go
When using `system` to get Windows system DNS, mihomo always get three same DNS. It's unnecessary and redundant, so just reserve unique one.
=> fix redundant WindowsDNS

config/config.go
This adds `json` struct tags for more fields in `config.RawConfig` to enable applications like CMFA to manage features such as external controllers using JSON config overrides.
=> feat: add `json` struct tags for more fields in `config.RawConfig`

tunnel/tunnel.go
当前 UDP 转发的实现是，将 UDP 报文收到一个 channel 内，然后启动多个 worker 一并 poll 该 channel. 这样一来，同一条 UDP 连接的包可能被不同的 worker 收走，worker 内又没有保序机制，由于 worker 的异步特性，最终导致发出的 UDP 包乱序。
虽然说 UDP 不提供任何顺序保证，但乱序还是会不可避免地导致上层感受到的延迟经常跳动，还是会影响使用体验。因此，能够避免的乱序还是最好要避免。特别是，即便专门采用了能够保证底层有序的传输通道，这里的问题会导致发出的包仍然乱序，这样也是比较难接受的。
本提交参考网卡的 RSS 机制，将 queue 分为每个 worker 一个，将传入的包的 IP 地址、端口、协议进行哈希（实际因为都是 UDP，所以不再计算协议），然后根据哈希结果将包分配到一个 queue、一个 worker 去处理，这样对于同一条连接的包就可以保证都在一个 worker 中处理，借此解决乱序问题。
性能方面我预计是没有明显影响的，因为以前 natTable 里面每条连接也有锁，导致以前的单连接转发性能也有单 worker 瓶颈。多连接性能至少是不受影响，且因为锁的争抢减少乃至消失，甚至还可能有提升。新引入的哈希代码会有一些开销，但是相比后面的加解密部分，这里的开销应当可以忽略不计。
---
这基本上算是我第一次接触 Go 语言，如有问题，请不吝赐教。谢谢！
=> feat: deliver UDP packets from same connection in receiving order

component/sniffer/dispatcher.go, component/sniffer/tls_sniffer.go
Problem:
When the length of the ClientHello message exceeds the TCP MSS (usually 1460 or 1448), due to the fragmentation of the ClientHello message during transmission, it may prevent TLSSniffer from obtaining sufficient data in first peek to parse the packet, leading to parsing failure.
Solution: 
During the TLS Sniffer parsing process, the required packet length can be determined. If the first parsing attempt fails, a retry can be initiated. Within a timeout period, once the data of the corresponding length is obtained, re-parsing can be performed.
=> Fix the issue where TLS Sniffer fails when the length of the ClientHello packet exceeds the TCP MSS

log/log.go
=> align time fields in logs

tunnel/tunnel.go
TCP handshake traffic should be counted as upload traffic for the remote connection
=> fix remote conn statistic error

adapter/provider/provider.go, adapter/provider/subscription_info.go
获取 proxy provider 信息的 API 返回值里 `subscriptionInfo` 没有的情况应该是不发送这个 `field`，而 72a126e5809acae4e9058c51f4e883dc7c8c6e19 之后现在会发送一个里面全 0 的 struct
这个 PR 把这个行为恢复到和 72a126e5809acae4e9058c51f4e883dc7c8c6e19 之前一样
=> fix: empty proxy provider subscription info not omitted

component/sniffer/dispatcher.go
When a domain matches forceDomain:
- SkipList is not checked
- Failed attempts are not cached
- Sniffing is attempted every time
This ensures forced domains are always sniffed regardless of previous failures.
优化 SNI 代理的嗅探行为
当使用 tunnel 和 sniffer 功能实现 SNI 代理时，发现一个问题：
- 由于代理目标地址相同，某些未知加密流量在 sniffer 失败几次后会被缓存为失败记录
- 这导致后续相同流量会跳过嗅探，使代理失效
解决方案：
- 使用 forceDomain 参数强制跳过 sniffer 的失败缓存机制
- 确保所有流量都能被正确嗅探，维持代理功能的正常运作
相关配置示例：
```
tunnels: # one line config
- tcp,0.0.0.0:443,fake-domain.com:443
- udp,0.0.0.0:443,fake-domain.com:443
- tcp,0.0.0.0:80,fake-domain.com:80
- tcp,192.168.51.1:22,github.com:22
sniffer:
enable: true
force-dns-mapping: false
parse-pure-ip: false
override-destination: true
sniff:
HTTP:
ports: [80]
TLS:
ports: [443]
QUIC:
ports: [443]
force-domain:
- fake-domain.com
skip-domain:
- …
```
=> feat(sniffer): ensure forced domains are always sniffed

component/updater/update_ui.go
When download/update dashboard UI
- Compressed files with multiple root dir struct will extract files into mihomo homedir, which not only pollutes the work dir, but also can't extract the files to correct location setting in the config.
- Also add tgz format support.
=> extracting compressed files to correct location

dns/doh.go
增加了 dohMaxConnsPerHost 的值，防止 Go panic
参考：https://github.com/AdguardTeam/dnsproxy/issues/278
Fixes: https://github.com/MetaCubeX/mihomo/issues/573
=> Increase MaxConnsPerHost for DoH

listener/anytls/server.go, transport/anytls/client.go, transport/anytls/pipe/deadline.go, transport/anytls/pipe/io_pipe.go, transport/anytls/session/client.go, transport/anytls/session/session.go, transport/anytls/session/stream.go
Some server implementations require these methods to implement proxy stream sniffing.
Prevent memory leak.
Prevent subsequent misuse.
=> chore: update anytls
