adapter/outbound/vless.go

Adopted from ClashDotNetFramework/experimental-clash

Update vless.go, fix udp blocked

---

README.md

add the sample of Trojan + Xtls

 add trojan xtls sample

---

README.md

how to build the Clash.Meta locally

 add the doc of local build

---

adapter/outboundgroup/common.go
adapter/provider/provider.go
go.mod
go.sum

Replace the regexp implementation of the filter for proxy-providers and proxy-groups with regexp2

Full regexp support

---

adapter/outboundgroup/common.go
constant/adapters.go

Fix the filter under proxy-group to filter other groups

Fix the filter under proxy-group to filter other groups

---

config/config.go

Only prompt when interface cannot be found

Only prompt when interface cannot be found

---

config/config.go
hub/executor/executor.go
rule/provider/parse.go
rule/provider/provider.go

[Fix] skip when country code not found in GeoIP.dat

[Fix] skip when country code not found in GeoIP.dat

---

.github/workflows/docker.yaml
Dockerfile
check_amd64.sh

need to set environtments:
- DOCKERHUB_ACCOUNT
- DOCKERHUB_REPO
secrets:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN

Add docker workflow

---

config/config.go
go.mod
go.sum
hub/executor/executor.go
listener/http/server.go
listener/listener.go
listener/mixed/mixed.go
listener/socks/tcp.go

inbound-tfo: true #http&socks&mixed入站端口增加TFO
linux执行下面的命令生效
echo 3 > /proc/sys/net/ipv4/tcp_fastopen

入站增加TFO支持(默认不开启)

---

common/convert/base64.go
common/convert/converter.go
common/convert/v.go

1. Fix converter V2RayN-styled VMess security field typo
2. Add VMessAEAD standard support

feat: Update Converter

---

Dockerfile

support the iptables feature when running in docker
iptables:
enable: true

Add iptables package to docker

---

adapter/outbound/hysteria.go

BREAKING CHANGE: `alpn` changed from string to list

Chore: compatible with Stash hysteria config

---

config/config.go
constant/dns.go
dns/doh.go
dns/doq.go
dns/resolver.go
dns/util.go

DoH support perfer and force HTTP/3

featrue: DoH and DoQ are implemented using AdGuardTeam/dnsProxy

---

adapter/outbound/hysteria.go
transport/hysteria/conns/udp/hop.go
transport/hysteria/core/client.go
transport/hysteria/transport/client.go

add support for hysteria udp port hopping

add support for hysteria udp port hopping

---

listener/redir/tcp_linux.go

https://github.com/Dreamacro/clash/issues/2428

linux ipv6 REDIRECT

---

adapter/outboundgroup/groupbase.go
adapter/provider/provider.go
common/convert/converter.go
common/convert/v.go

fix:https://github.com/MetaCubeX/Clash.Meta/issues/345

make ConvertsV2Ray more robust

---

adapter/outboundgroup/loadbalance.go

fix: RoundRobin strategy of load balance when called multiple times

---

hub/route/server.go
tunnel/statistic/manager.go

feat: core support memory chat

feat: core support memory chat

---

hub/route/server.go

fix: chat.js not begin with zero

fix: chat.js not begin with zero

---

listener/sing_tun/dns.go

fix: tun warn timeout

---

.github/workflows/build.yml

https://github.com/MetaCubeX/Clash.Meta/actions/runs/4954104707/jobs/8862365672#step:6:1
https://github.com/MetaCubeX/Clash.Meta/actions/runs/4954104707/jobs/8862365672#step:7:1
https://github.com/MetaCubeX/Clash.Meta/actions/runs/4954104707/jobs/8862365672#step:9:1
https://github.com/MetaCubeX/Clash.Meta/actions/runs/4954104707/jobs/8862365672#step:10:1
these warm

fix deprecated command from docker

---

.golangci.yaml
Makefile
adapter/outboundgroup/parser.go
adapter/provider/parser.go
component/process/process_windows.go
config/config.go
constant/path.go
dns/resolver.go
dns/util.go
go.mod
hub/route/server.go
listener/redir/tcp_freebsd.go

Feature: support basic authentication for DoH
Fix: Adjust DNS TTL values based on minimum value
Fix: potential vulnerability in http provider
Fix: potential token time attack
Chore: more parse proxy group error detail
Chore: update go version to 1.20

Something update from clash :)

---

adapter/adapter.go
common/pool/alloc.go
common/pool/alloc_test.go

[Chore: add alive for proxy api](https://github.com/Dreamacro/clash/commit/31fe77ee694d9be3a2db0be59189f18a4d601759)
[Improve: alloc using make if alloc size > 65536](https://github.com/Dreamacro/clash/commit/154cb1d1f046ddc48d9ff76183698ef3a72bf01e)

Chore: Something update from clash

---

dns/enhancer.go
dns/middleware.go

https://github.com/Dreamacro/clash/commit/c1d027d6d1e6b9db7205ad74a4554c96822110bb

Fix: mapping dns should not stale

---

component/dialer/dialer.go

When no ipv6 addresses and ipv4 connect failed, it will append `connect failed: no ip address` ipv6 error wich is confusing

Fix dualStack confusing error on ipv4 failed connect

---

main.go

Backport Clash feature by @septs, see Dreamacro/clash#2908

feat: add reload signal support

---

.github/workflows/android-branch-sync.yml

两种情况下触发：
1. push带version tag的commit（新版本）
2. 新PR合并

Add auto sync Alpha -> android-open

---

.github/workflows/android-branch-auto-sync.yml
.github/workflows/android-open-auto-sync.yml

每次达到触发条件（两边任何一边有push/tag/PR合并），以Alpha为底rebase一遍android-open，将合并完的force push到android-real。
中途遇到冲突则打断并报错

Add auto sync Alpha rebase android-open -> android-real

---

hub/route/external.go
hub/route/server.go

Support external programs to extend the kernel's API

feat: support external api extensions

---

rules/logic/logic.go

close: #876 
我是Golang新手，所以写的代码可能有些问题（两个循环复用性有点差了），希望大佬们见谅，但是基本修复思路应该是正确的🤣

fix: SUB-RULE with PROCESS-NAME rule payload not working

---

component/iface/iface.go

better practice for code concision

chore: stylish d2ae94f2

---

component/process/process_darwin.go

see: https://github.com/MetaCubeX/mihomo/issues/1392

optimize: reduce func findProcessName mem allocs and copy

---

adapter/adapter.go
adapter/outbound/base.go
adapter/outbound/singmux.go
adapter/outbound/wireguard.go
constant/adapters.go

chore: restful api display smux and mptcp

---

hub/route/server.go
hub/route/upgrade.go

chore: allow upgrade ui in embed mode

---

go.mod
go.sum

Fix a deadlock in mieru protocol implementation.
Tested: https://github.com/enfein/mieru/actions/runs/12573599607/job/35046780241

chore: update mieru version
